# Generated by Django 4.2.7 on 2023-12-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(to='tracker_app.type', verbose_name='Тип'),
        ),
    ]
